algorithm: meanteacher
save_dir: ./saved_models/usb_cv/
save_name: meanteacher_mydataset
resume: False
load_path: ./saved_models/usb_cv//meanteacher_mydataset/latest_model.pth
overwrite: True
use_tensorboard: False
use_wandb: True
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 3000
uratio: 2
ema_m: 0.999
ulb_loss_ratio: 50
unsup_warm_up: 0.4
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.001
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch16_224
net_from_name: False
data_dir: /d9lab/songjie/datasets
dataset: mydataset_semi/sample_images
train_sampler: RandomSampler
num_classes: 6
num_workers: 6
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10041
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth
